@echo off
REM WH1/WH2: same hot-reload pin file (cp10-cp95 only; no fresh start).
set RE1_YAWN_RESET_PIN_FILE=data\workhorse_reset_pin.env
set RE1_YAWN_RESET_PIN_INDEX=
set RE1_YAWN_RESET_PIN_RANGE=
set RE1_YAWN_RESET_PIN_SET=
set RE1_YAWN_RESET_PIN_SET_WEIGHT=
set RE1_YAWN_RESET_PIN_WEIGHTS=
set RE1_YAWN_FIGHT_BIAS_INDEX=
set RE1_YAWN_FIGHT_BIAS_WEIGHT=
