@echo off
REM Pin cp120->cp121 hunt + leg-replay tapes for footage-quality captures.
set RE1_YAWN_RESET_PIN_FILE=data\yawn_cp120_grind.env
set RE1_YAWN_LEG_REPLAY=1
set RE1_YAWN_EXTEND_EPISODE_ON_CELL=1
set RE1_YAWN_PAYFORWARD_RIPPLE=0
set RE1_YAWN_RESET_FRONTIER_FIGHT_ONLY=
set RE1_YAWN_RESET_PIN_INDEX=
set RE1_YAWN_RESET_PIN_SET=
set RE1_YAWN_RESET_PIN_SET_WEIGHT=
set RE1_YAWN_RESET_PIN_RANGE=
set RE1_YAWN_RESET_PIN_WEIGHTS=
set RE1_YAWN_RESET_TRAINING_MIX=
set RE1_YAWN_PIN_MARCH=
